In [1]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [11]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [13]:
arr[5]

5

In [15]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [17]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [19]:
arr[0:5] = 100

In [21]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [23]:
arr = np.arange(0,11)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
slice_of_arr = arr[0:6]

In [29]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [33]:
slice_of_arr[:] = 99

In [35]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [37]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
# Slices are pointer redirects to the original array. Changing the slice will change the original array.

In [41]:
# To avoid this... Use the copy method

In [43]:
arr_copy = arr.copy()

In [45]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_copy[:] = 100

In [51]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [57]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [59]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [61]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [63]:
arr_2d[0][0]

5

In [65]:
arr_2d[0]

array([ 5, 10, 15])

In [67]:
arr_2d[1][1]

25

In [71]:
arr_2d[0][2]

15

In [73]:
arr_2d[2][1]

40

In [75]:
arr_2d[1][2]

30

In [79]:
arr_2d[2,1]

40

In [81]:
arr_2d[1,2]

30

In [83]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [95]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [97]:
arr_2d[0:,:1]

array([[ 5],
       [20],
       [35]])

In [99]:
arr_2d[0,:1]

array([5])

In [101]:
arr = np.arange(1,11)

In [103]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [107]:
bool_arr = arr < 5

In [111]:
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [113]:
arr[bool_arr]

array([1, 2, 3, 4])

In [117]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [119]:
arr[arr<3]

array([1, 2])

In [121]:
# Above syntax is frequently leveraged with pandas

In [125]:
arr_2d = np.arange(50).reshape(5,10)

In [127]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [133]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [129]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [137]:
arr_2d[3:5,7:10]

array([[37, 38, 39],
       [47, 48, 49]])

In [151]:
arr_2d[arr_2d<39]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38])