NumPy Arrays

In [1]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [7]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

In [11]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [13]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
mat = np.array(my_mat)

In [17]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [33]:
np.zeros(3)

array([0., 0., 0.])

In [35]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [43]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [45]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
np.random.rand(5)

array([0.32001072, 0.96952251, 0.32012316, 0.72925897, 0.92147147])

In [49]:
np.random.rand(5,5)

array([[0.77771398, 0.11080512, 0.22152886, 0.63475183, 0.68096648],
       [0.94196574, 0.53517717, 0.4964898 , 0.43325747, 0.86140145],
       [0.50303007, 0.32566653, 0.70259117, 0.68887138, 0.6814769 ],
       [0.20795237, 0.25721045, 0.77158838, 0.25656813, 0.26915531],
       [0.49235415, 0.33354126, 0.58746281, 0.66380357, 0.31422282]])

In [53]:
np.random.randn(2)

array([-0.46471069,  1.36305714])

In [55]:
np.random.randn(4,4)

array([[ 0.36649697,  0.40935447,  0.9342637 , -1.13139984],
       [ 0.82711629,  0.79339873,  0.67322551,  2.15613587],
       [ 0.99789382, -0.34595965, -0.73055211,  0.60244053],
       [ 0.89470999, -1.75866595, -1.44091156, -0.78364795]])

In [57]:
np.random.randint(1,100)

17

In [59]:
np.random.randint(1,100,10)

array([33, 97, 78, 96, 21, 42, 67, 31, 98, 56])

In [61]:
arr = np.arange(25)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
ranarr = np.random.randint(0,50,10)

In [67]:
ranarr

array([33,  5, 49, 30, 34, 13, 13, 21,  4, 15])

In [73]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [77]:
prime_arr = np.arange(13)

In [81]:
prime_arr.reshape(6,2)

ValueError: cannot reshape array of size 13 into shape (6,2)

In [83]:
ranarr.max()

49

In [85]:
ranarr.min()

4

In [89]:
ranarr

array([33,  5, 49, 30, 34, 13, 13, 21,  4, 15])

In [91]:
ranarr.argmax()

2

In [93]:
ranarr.argmin()

8

In [95]:
arr.shape

(25,)

In [97]:
arr = arr.reshape(5,5)

In [99]:
arr.shape

(5, 5)

In [101]:
arr.dtype

dtype('int32')

In [103]:
from numpy.random import randint

In [105]:
randint(2,10)

2